import pyautogui as pg
import time

pg.FAILSAFE = False

time.sleep(5)
for i in range (1000000000000000000000):
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    time.sleep(5)
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    time.sleep(20)
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    pg.write("println!('Hello this is from rust')")
    pg.press('Enter')
    time.sleep(20)
