version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: .
    container_name: golang-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - rabbitmq

networks:
  default:
    driver: bridge
